version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      - CLICKHOUSE_USER=default_user
      - CLICKHOUSE_PASSWORD=default_test
    restart: unless-stopped
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - clickhouse_network

volumes:
  clickhouse_data:

networks:
  clickhouse_network:
    driver: bridge