# Copyright 2025-present DatusAI, Inc.
# Licensed under the Apache License, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.

"""Tests for OceanBase Oracle MigrationTargetMixin implementation."""

import pytest

from datus_db_core import MigrationTargetMixin
from datus_oceanbase_oracle import OceanBaseOracleConnector


@pytest.fixture
def connector():
    return OceanBaseOracleConnector.__new__(OceanBaseOracleConnector)


class TestMixinInheritance:
    def test_is_migration_target(self, connector):
        assert isinstance(connector, MigrationTargetMixin)


class TestDescribeMigrationCapabilities:
    def test_supported_true(self, connector):
        result = connector.describe_migration_capabilities()
        assert result["supported"] is True

    def test_dialect_family_oracle_like(self, connector):
        result = connector.describe_migration_capabilities()
        assert result["dialect_family"] == "oracle-like"

    def test_no_hard_requirements(self, connector):
        result = connector.describe_migration_capabilities()
        assert result["requires"] == []

    def test_type_hints_include_identity(self, connector):
        result = connector.describe_migration_capabilities()
        hints_str = " ".join(result["type_hints"].values()).upper()
        assert "IDENTITY" in hints_str

    def test_example_ddl_is_create_table(self, connector):
        result = connector.describe_migration_capabilities()
        ddl = result["example_ddl"].upper()
        assert "CREATE TABLE" in ddl
        assert "DUPLICATE KEY" not in ddl
        assert "BUCKETS" not in ddl


class TestValidateDdl:
    def test_accepts_standard_oracle_ddl(self, connector):
        ddl = 'CREATE TABLE "SCHEMA"."T" ("ID" NUMBER PRIMARY KEY, "NAME" VARCHAR2(255))'
        assert connector.validate_ddl(ddl) == []

    def test_rejects_duplicate_key_starrocks_syntax(self, connector):
        ddl = 'CREATE TABLE "T" ("ID" BIGINT) DUPLICATE KEY("ID")'
        errors = connector.validate_ddl(ddl)
        assert any("DUPLICATE KEY" in e.upper() or "STARROCKS" in e.upper() for e in errors)

    def test_rejects_distributed_by_hash_buckets(self, connector):
        ddl = 'CREATE TABLE "T" ("ID" BIGINT) DISTRIBUTED BY HASH("ID") BUCKETS 10'
        errors = connector.validate_ddl(ddl)
        assert any("BUCKETS" in e.upper() or "STARROCKS" in e.upper() for e in errors)

    def test_rejects_engine_clause(self, connector):
        ddl = "CREATE TABLE t (id INT) ENGINE=InnoDB"
        errors = connector.validate_ddl(ddl)
        assert any("ENGINE" in e.upper() for e in errors)

    def test_rejects_auto_increment(self, connector):
        ddl = "CREATE TABLE t (id INT AUTO_INCREMENT PRIMARY KEY)"
        errors = connector.validate_ddl(ddl)
        assert any("AUTO_INCREMENT" in e for e in errors)

    def test_accepts_identity_column(self, connector):
        ddl = 'CREATE TABLE "T" ("ID" NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY)'
        assert connector.validate_ddl(ddl) == []


class TestSuggestTableLayout:
    def test_returns_empty_dict(self, connector):
        columns = [
            {"name": "id", "type": "NUMBER", "nullable": False},
            {"name": "name", "type": "VARCHAR2(255)", "nullable": True},
        ]
        layout = connector.suggest_table_layout(columns)
        assert layout == {}


class TestMapSourceType:
    def test_hugeint_to_number(self, connector):
        assert connector.map_source_type("duckdb", "HUGEINT") == "NUMBER(38,0)"

    def test_largeint_to_number(self, connector):
        assert connector.map_source_type("duckdb", "LARGEINT") == "NUMBER(38,0)"

    def test_boolean_to_number(self, connector):
        assert connector.map_source_type("duckdb", "BOOLEAN") == "NUMBER(1)"

    def test_auto_increment_to_identity(self, connector):
        assert connector.map_source_type("mysql", "AUTO_INCREMENT") == "NUMBER GENERATED BY DEFAULT AS IDENTITY"

    def test_serial_to_identity(self, connector):
        assert connector.map_source_type("postgresql", "SERIAL") == "NUMBER GENERATED BY DEFAULT AS IDENTITY"

    def test_text_to_clob(self, connector):
        assert connector.map_source_type("mysql", "TEXT") == "CLOB"

    def test_json_to_clob(self, connector):
        assert connector.map_source_type("postgresql", "JSONB") == "CLOB"

    def test_float_to_binary_float(self, connector):
        assert connector.map_source_type("mysql", "FLOAT") == "BINARY_FLOAT"

    def test_double_to_binary_double(self, connector):
        assert connector.map_source_type("mysql", "DOUBLE") == "BINARY_DOUBLE"

    def test_enum_to_varchar2(self, connector):
        assert connector.map_source_type("mysql", "ENUM") == "VARCHAR2(255)"

    def test_type_with_precision(self, connector):
        assert connector.map_source_type("mysql", "BIGINT(20)") == "NUMBER(19)"

    def test_unknown_returns_none(self, connector):
        assert connector.map_source_type("duckdb", "VARCHAR") is None
